version: '3.8'
services:
  postgreDB:
    image: postgres
    container_name: postgresql-db
    restart: always
    ports:
      - 5432:5432
    environment:
      - POSTGRES_USER=${DB_USER}
      - POSTGRES_DB=${DB_NAME}
      - POSTGRES_PASSWORD=${DB_PASSWORD}
    volumes:
      - ./postgresql:/var/lib/postgresql/data